server:
  port: 8082

spring:
  application:
    name: my-second-service

eureka:
  client: # eureka 클라이언트 등록
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
